Ability to turn on verbose mode for ssh command.
Fixes #18.

diff --git a/bin/shipit b/bin/shipit
--- a/bin/shipit
+++ b/bin/shipit
@@ -2,7 +2,7 @@
 
 #
 # Minimalistic SSH deployment.
-# 
+#
 # Author: Artem Sapegin, sapegin.me
 # License: MIT
 #
@@ -17,6 +17,7 @@ CONFIG=./.shipit
 TARGET=deploy
 SSH_HOST=
 SSH_PATH=
+VERBOSE=
 
 # Common stuff
 RED="$(tput setaf 1)"
@@ -38,6 +39,7 @@ usage() {
 	echo "Options:"
 	echo
 	echo "    -V, --version    Print program version"
+	echo "    -v, --verbose    Enable verbose mode for SSH"
 	echo "    -h, --help       Print help (this screen)"
 	echo
 	echo "Commands:"
@@ -62,6 +64,14 @@ version() {
 	echo "`basename $0` v$VERSION"
 }
 
+# Enable verbose mode
+verbose() {
+	echo "$WHITE"
+	echo "Verbose mode is on!"
+	echo "$NOCOLOR"
+	VERBOSE="1"
+}
+
 # Print squirrel
 squirrel() {
 	echo "$WHITE"
@@ -75,7 +85,7 @@ squirrel() {
 # Read and validate config file
 read_config() {
 	# Check config file existance
-	test -f $CONFIG || abort "Config file $CONFIG not found." 
+	test -f $CONFIG || abort "Config file $CONFIG not found."
 
 	# Read and eval first section
 	local config=`awk '/^/ {print; exit}' RS= $CONFIG`
@@ -85,7 +95,7 @@ read_config() {
 	test -z "$host" && incomplete_config 'host'
 	test -z "$path" && incomplete_config 'path'
 	test -z "$host" || test -z "$path" && exit 1
-	
+
 	# Expose params
 	SSH_HOST=$host
 	SSH_PATH=$path
@@ -112,7 +122,7 @@ deploy() {
 		header "Running local script..."
 		run_local "$local_script"
 		if [ $? -ne 0 ]; then
-			abort "Deploy wasn’t successful: local script failed."	
+			abort "Deploy wasn’t successful: local script failed."
 		fi
 	fi
 
@@ -122,7 +132,7 @@ deploy() {
 		header "Running remote script at $SSH_HOST..."
 		run_remote "$remote_script"
 		if [ $? -ne 0 ]; then
-			abort "Deploy wasn’t successful: remote script failed."	
+			abort "Deploy wasn’t successful: remote script failed."
 		fi
 	fi
 
@@ -150,7 +160,14 @@ run_remote() {
 		cd \"$SSH_PATH\"
 		$1
 	"""
-	ssh -A $2 "$SSH_HOST" "$script"
+
+	local verbose=
+
+	if [ -n "$VERBOSE" ]; then
+		verbose="-v"
+	fi
+
+	ssh $verbose -A $2 "$SSH_HOST" "$script"
 }
 
 # Run local script
@@ -185,7 +202,7 @@ exec_command() {
 # Copy local file to remote host
 copy_to_remote() {
 	read_config
-	test -f "$1" || abort "Local file $1 not found." 
+	test -f "$1" || abort "Local file $1 not found."
 	header "Copying $1 to $SSH_HOST..."
 	scp "$1" "$SSH_HOST:$SSH_PATH/$1"
 }
@@ -194,18 +211,18 @@ copy_to_remote() {
 ########################################################################################################################
 
 # Parse CLI arguments
-arg=$1; shift
-if [ -n "$arg" ]; then
-	case $arg in
+for arg in "$@"; do
+	case "$arg" in
 		-h|--help) usage; exit ;;
 		-V|--version) version; exit ;;
+		-v|--verbose) verbose; ;;
 		list|ls) list_targets; exit ;;
 		console|shell|ssh) open_console; exit ;;
 		exec|run) exec_command "$@"; exit ;;
 		copy|cp) copy_to_remote "$@"; exit ;;
 		*) TARGET="$arg" ;;
 	esac
-fi
+done
 
 # Run specified target
 deploy
